org: datamotion
service: stepfunctionhelloworld

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs20.x

functions:
  add:
    handler: handler.add

  double:
    handler: handler.double

  doubleBigNumbers:
    handler: handler.doubleBigNumbers

stepFunctions:
  stateMachines:
    simple-maths:
      name: simple-maths
      definition:
        Comment: "Example to demonstrate chaining functions"
        StartAt: Add
        States:
          Add:
            Type: Task
            Resource:
              Fn::GetAtt: [add, Arn]
            Next: IsBigNumber
          IsBigNumber:
            Type: Choice
            Choices:
              - Variable: $
                NumericGreaterThan: 50
                Next: DoubleBigNumbers
            Default: Double
          Double:
            Type: Task
            Resource:
              Fn::GetAtt: [double, Arn]
            End: true
            Retry:
              - ErrorEquals: [NumberIsTooBig]
                MaxAttempts: 0
              - ErrorEquals: [States.ALL]
                MaxAttempts: 3
            Catch:
              - ErrorEquals: [NumberIsTooBig]
                Next: DoubleBigNumbers
          DoubleBigNumbers:
            Type: Task
            Resource:
              Fn::GetAtt: [doubleBigNumbers, Arn]
            End: true
